# Define job order
stages:
  - lib-build
  - lib-deploy

# Global variables. Can be used by any jobs
variables:
  VS_CMAKE_GENERATOR: "Visual Studio 15 2017"
  DEPLOYMENT_WINDOWS_NET_SHARE: "\\\\autan\\gitlab_workspace\\dependencies"

# Create library for macos
lib-build-macos:
  stage: lib-build
  tags:
    - osx
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_DRAFTS=ON -DCMAKE_PREFIX_PATH=$HOME/builds/sysroot/usr/local/
    - make -j8 -C build
  artifacts:
    paths:
      - build
    name: "lib-build-macos"
    expire_in: 1 day
  dependencies: []

lib-deploy-macos:
  stage: lib-deploy
  tags:
    - osx
  script:
    - make -C build DESTDIR=$HOME/builds/sysroot/ install
  dependencies:
    - lib-build-macos
  needs:
    - lib-build-macos
  only:
    refs:
      - master
    variables:
      - $CI_PROJECT_ROOT_NAMESPACE == "ingescape"
  
# Create library for windows
# Library will be build for 4 targets : Debug x86, Debug x64, Release x86, Release x64
lib-build-windows:
  stage: lib-build
  tags:
    - windows
  script:
    - IF (!$env:VS_VERSION_YEAR) { ECHO ">> VS_VERSION_YEAR must be defined on the Runner side <<" ; EXIT 1 } 
    - IF (!$env:VS_VERSION_NUM) { ECHO ">> VS_VERSION_NUM must be defined on the Runner side <<" ; EXIT 1 }
    - $env:INITIAL_PATH="$env:PATH;$env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\include"
    - mkdir build
    - cd build
    - $env:PATH="$env:INITIAL_PATH;$env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Debug\x86"
    - cmake -S .. -B DebugX86 -G"$env:VS_CMAKE_GENERATOR" -DENABLE_DRAFTS=ON -DCZMQ_BUILD_STATIC=OFF
    - cmake --build DebugX86 --target ALL_BUILD --config Debug
    - $env:PATH="$env:INITIAL_PATH;$env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Release\x86"
    - cmake -S .. -B ReleaseX86 -G"$env:VS_CMAKE_GENERATOR" -DENABLE_DRAFTS=ON -DCZMQ_BUILD_STATIC=OFF
    - cmake --build ReleaseX86 --target ALL_BUILD --config Release
    - $env:PATH="$env:INITIAL_PATH;$env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Debug\x64"
    - cmake -S .. -B DebugX64 -G"$env:VS_CMAKE_GENERATOR Win64" -DENABLE_DRAFTS=ON -DCZMQ_BUILD_STATIC=OFF
    - cmake --build DebugX64 --target ALL_BUILD --config Debug
    - $env:PATH="$env:INITIAL_PATH;$env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Release\x64"
    - cmake -S .. -B ReleaseX64 -G"$env:VS_CMAKE_GENERATOR Win64" -DENABLE_DRAFTS=ON -DCZMQ_BUILD_STATIC=OFF
    - cmake --build ReleaseX64 --target ALL_BUILD --config Release
  artifacts:
    paths:
      - build
    name: "lib-build-windows"
    expire_in: 1 day
  dependencies: []
    
lib-deploy-windows:
  stage: lib-deploy
  tags:
    - windows
  script:
    - cd build
    - cmake --install DebugX86 --config Debug --prefix $env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Debug\x86
    - cmake --install ReleaseX86 --config Release --prefix $env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Release\x86
    - cmake --install DebugX64 --config Debug --prefix $env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Debug\x64
    - cmake --install ReleaseX64 --config Release --prefix $env:DEPLOYMENT_WINDOWS_NET_SHARE\Builds\Release\x64
  dependencies:
    - lib-build-windows
  needs:
    - lib-build-windows
  only:
    refs:
      - master
    variables:
      - $CI_PROJECT_ROOT_NAMESPACE == "ingescape"

# Create library for linux
lib-build-linux:
  stage: lib-build
  image: ingescape/debian-testing-compil
  tags:
    - docker
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_DRAFTS=ON -DCMAKE_PREFIX_PATH=$HOME/builds/release/linux_x64/usr/local/
    - make -C build
  artifacts:
    paths:
      - build
    name: "lib-build-linux-x64"
    expire_in: 1 day
  dependencies: []

lib-deploy-linux:
  stage: lib-deploy
  image: ingescape/debian-testing-compil
  tags:
    - docker
  script:
    - make -C build DESTDIR=$HOME/builds/release/linux_x64/ install
  dependencies:
    - lib-build-linux
  needs:
    - lib-build-linux
  only:
    refs:
      - master
    variables:
      - $CI_PROJECT_ROOT_NAMESPACE == "ingescape"

# Create library for CentOS with qt
lib-build-centos-qt:
  stage: lib-build
  tags:
    - centos-qt
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_DRAFTS=ON -DCMAKE_PREFIX_PATH=/builds/sysroot/usr/local/
    - make -C build
  artifacts:
    paths:
      - build
    name: "lib-build-linux-x64"
    expire_in: 1 day
  dependencies: []

lib-deploy-centos-qt:
  stage: lib-deploy
  tags:
    - centos-qt
  script:
    - make -C build DESTDIR=/builds/sysroot/ install
  dependencies:
    - lib-build-centos-qt
  needs:
    - lib-build-centos-qt
  only:
    refs:
      - master
    variables:
      - $CI_PROJECT_ROOT_NAMESPACE == "ingescape"

