#! /bin/bash
#
#   mkmans - rebuild man pages
#
#   Author: Pieter Hintjens <ph@imatix.com>
#   License: public domain
#
#   syntax: mkmans
#

make --quiet
rm -f *.xml    #   Makefile does not detect version differences for XML
for FILE in z*.txt; do 
    ./mkman $FILE
    make `basename $FILE .txt`.xml
done

