/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "czmq.h"
#include "../../native/include/org_zeromq_czmq_Ziflist.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Ziflist__1_1init (JNIEnv *env, jclass c) {
    ziflist_t *self = ziflist_new ();
    if (self)
        return (jlong) self;
    return -1;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Ziflist__1_1destroy (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    ziflist_destroy (&self);
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Ziflist__1_1reload (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    void rc = ziflist_reload (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Ziflist__1_1size (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    size_t rc = ziflist_size (self);
    return rc;
}

JNIEXPORT jstring JNICALL
Java_org_zeromq_czmq_Ziflist__1_1first (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    const char * rc = ziflist_first (self);
    return rc;
}

JNIEXPORT jstring JNICALL
Java_org_zeromq_czmq_Ziflist__1_1next (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    const char * rc = ziflist_next (self);
    return rc;
}

JNIEXPORT jstring JNICALL
Java_org_zeromq_czmq_Ziflist__1_1address (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    const char * rc = ziflist_address (self);
    return rc;
}

JNIEXPORT jstring JNICALL
Java_org_zeromq_czmq_Ziflist__1_1broadcast (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    const char * rc = ziflist_broadcast (self);
    return rc;
}

JNIEXPORT jstring JNICALL
Java_org_zeromq_czmq_Ziflist__1_1netmask (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    const char * rc = ziflist_netmask (self);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Ziflist__1_1print (JNIEnv *env, jclass c, jlong jself) {
    ziflist_t *self = (ziflist_t *) jself;
    void rc = ziflist_print (self);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Ziflist__1_1test (JNIEnv *env, jclass c, jlong jself, jboolean verbose) {
    ziflist_t *self = (ziflist_t *) jself;
    void rc = ziflist_test (verbose);
    return rc;
}

}
