/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "czmq.h"
#include "../../native/include/org_zeromq_czmq_Zhashx.h"

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1init (JNIEnv *env, jclass c) {
    zhashx_t *self = zhashx_new ();
    if (self)
        return (jlong) self;
    return -1;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zhashx__1_1destroy (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    zhashx_destroy (&self);
}

JNIEXPORT jint JNICALL
Java_org_zeromq_czmq_Zhashx__1_1insert (JNIEnv *env, jclass c, jlong jself, jlong key, jlong item) {
    zhashx_t *self = (zhashx_t *) jself;
    int rc = zhashx_insert (self, key, item);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zhashx__1_1update (JNIEnv *env, jclass c, jlong jself, jlong key, jlong item) {
    zhashx_t *self = (zhashx_t *) jself;
    void rc = zhashx_update (self, key, item);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zhashx__1_1delete (JNIEnv *env, jclass c, jlong jself, jlong key) {
    zhashx_t *self = (zhashx_t *) jself;
    void rc = zhashx_delete (self, key);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zhashx__1_1purge (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    void rc = zhashx_purge (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1lookup (JNIEnv *env, jclass c, jlong jself, jlong key) {
    zhashx_t *self = (zhashx_t *) jself;
    void * rc = zhashx_lookup (self, key);
    return rc;
}

JNIEXPORT jint JNICALL
Java_org_zeromq_czmq_Zhashx__1_1rename (JNIEnv *env, jclass c, jlong jself, jlong old key, jlong new key) {
    zhashx_t *self = (zhashx_t *) jself;
    int rc = zhashx_rename (self, oldKey, newKey);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1size (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    size_t rc = zhashx_size (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1keys (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    zlistx_t * rc = zhashx_keys (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1values (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    zlistx_t * rc = zhashx_values (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1first (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    void * rc = zhashx_first (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1next (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    void * rc = zhashx_next (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1cursor (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    const void * rc = zhashx_cursor (self);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zhashx__1_1comment (JNIEnv *env, jclass c, jlong jself, jstring format) {
    zhashx_t *self = (zhashx_t *) jself;
    void rc = zhashx_comment (self, format);
    return rc;
}

JNIEXPORT jint JNICALL
Java_org_zeromq_czmq_Zhashx__1_1save (JNIEnv *env, jclass c, jlong jself, jstring filename) {
    zhashx_t *self = (zhashx_t *) jself;
    int rc = zhashx_save (self, filename);
    return rc;
}

JNIEXPORT jint JNICALL
Java_org_zeromq_czmq_Zhashx__1_1load (JNIEnv *env, jclass c, jlong jself, jstring filename) {
    zhashx_t *self = (zhashx_t *) jself;
    int rc = zhashx_load (self, filename);
    return rc;
}

JNIEXPORT jint JNICALL
Java_org_zeromq_czmq_Zhashx__1_1refresh (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    int rc = zhashx_refresh (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1pack (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    zframe_t * rc = zhashx_pack (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1unpack (JNIEnv *env, jclass c, jlong jself, jlong frame) {
    zhashx_t *self = (zhashx_t *) jself;
    zhashx_t * rc = zhashx_unpack (frame);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1dup (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    zhashx_t * rc = zhashx_dup (self);
    return rc;
}

JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Zhashx__1_1dup_v2 (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    zhashx_t * rc = zhashx_dup_v2 (self);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zhashx__1_1autofree (JNIEnv *env, jclass c, jlong jself) {
    zhashx_t *self = (zhashx_t *) jself;
    void rc = zhashx_autofree (self);
    return rc;
}

JNIEXPORT void JNICALL
Java_org_zeromq_czmq_Zhashx__1_1test (JNIEnv *env, jclass c, jlong jself, jboolean verbose) {
    zhashx_t *self = (zhashx_t *) jself;
    void rc = zhashx_test (verbose);
    return rc;
}

}
