################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
try:
    from . import native
    lib = native.lib
    ffi = native.ffi
except ImportError:
    from . import dlopen
    lib = dlopen.lib
    ffi = dlopen.ffi

