The following ABNF grammar defines the zgossip protocol:

        C:HELLO [ *S:ANNOUNCE ]
        C:ANNOUNCE / S:ANNOUNCE / C:PING S:PONG

    ;         Client says hello to server
    hello           = signature %d1
    signature       = %xAA %xA0             ; two octets

    ;         Client or server announces a new service
    announce        = signature %d2 endpoint service
    endpoint        = string                ; ZeroMQ endpoint
    service         = string                ; Service name

    ;         Client signals liveness
    ping            = signature %d3

    ;         Server responds to ping
    pong            = signature %d4

    ;         Server rejects command as invalid
    invalid         = signature %d5

    ; Strings are always length + text contents
    string          = number-1 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
