The following ABNF grammar defines the zpubsub protocol:

    zpubsub_filter  = *(  FILTER )

    ;         A zpubsub filter.
    filter          = signature %d1 magic version partition topic
    signature       = %xAA %xA7             ; two octets
    magic           = number-2              ; Magic number
    version         = number-2              ; Version
    partition       = string                ; Partition name
    topic           = string                ; Topic name

    ; Strings are always length + text contents
    string          = number-1 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
